travis:
  secure:
    BINSTAR_TOKEN: CtkmwAu8g4OET+u5ChdsZw7OiZPL4a3nZgoR8YK2fRwWFotz56denYzcgT6ZM0RZ/I55+Lbky4MDVT7Mhjnezqg7s/fi4Fgyu7axRguMC+4JBAAq5eSZ/RrmWnSYt20/G31BsxehgZ59SzMr7wlDxpULkBfDmYBkgFv8Iuo9RMJpgN4pLbnjFiCwrYamhWEkiEFQCEV1WvRyruCglSMVhVTa/En1SyanKcyqLhytu3PrCAzU2gwlRwQhDshInWwGxG2+Rczm1WVeMuYL+qOTei7hB4+7f1HuQeEGk5k1X8TyKwCTfcODcIv5VG5G7fXWrB/VrcEFG+E2UAz0jOg+nxPe/mJ6u+WSdDJqHB8nwoATZwfd0FCtxP1rD4e2iIfjlpQhZlJ9C7SdoLTGiiUfzH/r296MFMwxovkfqL2IoTR4gtpTpFkoCKGGPPonfnNdFsURm66UEP/pM74ZO+7ViLuhVGpjHWUmc4O6Xx9i581A7ys6W8fit9dpuwtVwNy77dCEI7jhp15U1WCfDAbx8zlwU7gBQkdEnRePGCKYGZAfdea/pn3NBrNY4ao7wBkh5e+bTyOfo9OtZ2gPJvKeYjyCE4ZlQyffxCbyxIFK2eMXOOmPlV8Hrro2B0wLeYvCYbIeTguOv2mxHPcDkkceQ+ybIqDKynM+SCjLvHDBTcU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
